image: "node:latest"
stages:
 - construir
 - testar

construir:
  stage: construir
  script:
   - npm install
  artifacts:
    paths:
      - node_modules/*

testar:
  stage: testar
  script:
   - npm test