image: "node:latest"
stages:
 - construir
 - testar

construir:
  stage: construir
  artifacts:
    paths:
      node_modules
  script:
   - npm install

testar:
  stage: testar
  script:
   - npm test