image: "node:latest"

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
 - construir
 - testar

construir:
  stage: construir
  script:
   - npm install
  
testar:
  stage: testar
  script:
   - npm test