image: "node:latest"

stages:
 - construir
 - testar
 - publicar

construir:
  stage: construir
  script:
   - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

testar:
  stage: testar
  script:
   - npm test

publicar:
  stage: publicar
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/transfor-digital-modelo-devops.git
    - git push -f heroku HEAD:master
