image: "node:latest"


stages:
 - construir
 - testar

construir:
  stage: construir
  script:
   - npm install
  artifacts:
    paths:
      - node_modules/
  expire_in: 1 week

testar:
  stage: testar
  script:
   - npm test